language: go

go:
# - 1.x
  - master
before_script:
  - go vet github.com/argoproj/argo
  # Rename the repo to fix imports (/my/path/github.com/other-owner/argo -> /my/path/github.com/argoproj/argo)
  - pwd | grep -q "github.com/argoproj/argo"
      || target="$(pwd | sed 's/\(github.com\/\)[0-9a-zA-Z_-]*/\1argoproj/g')"
        && mkdir -p "$(dirname "$target")"
        && cp -r "$(pwd)"  "$target"
script:
  - printenv
  - go test -coverprofile=coverage.out -v github.com/argoproj/argo/workflow/... github.com/argoproj/argo/util/... github.com/argoproj/argo/cmd/...
