language: go

go:
# - 1.x
  - master
before_script:
  - go vet github.com/CyrusBiotechnology/argo
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
script:
  - sh -c 'pwd'
  - go test -coverprofile=coverage.out -v github.com/CyrusBiotechnology/argo/workflow/... github.com/CyrusBiotechnology/argo/util/... github.com/CyrusBiotechnology/argo/cmd/...
