language: go

go:
# - 1.x
  - master
before_script:
  - go vet github.com/CyrusBiotechnology/argo
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
script:
  # Rename the repo to fix imports (/my/path/github.com/other-owner/argo -> /my/path/github.com/argoproj/argo)
  - sh -c 'pwd | grep -q "github.com/argoproj/argo" || target="$(pwd | sed 's/\(github.com\/\)[0-9a-zA-Z_-]*/\1argoproj/g')" && mkdir "$(dirname "$target")" && ln -s "$(pwd)"  "$(pwd | sed 's/\(github.com\/\)[0-9a-zA-Z_-]*/\1argoproj/g')" '
  - go test -coverprofile=coverage.out -v github.com/CyrusBiotechnology/argo/workflow/... github.com/CyrusBiotechnology/argo/util/... github.com/CyrusBiotechnology/argo/cmd/...
